%YAML:1.0
date: "Sun Aug 26 21:19:53 2012\n"
# gui dimension
ui_width: 960
ui_height: 720
# image thumbnail on gui 
thumb_width: 128
thumb_height: 72
# the image used within the pipeline
#im_width: 640
#im_height: 360
#im_height: 480
#im_width: 800
#im_height: 600
im_width: 1280
im_height: 720
#im_width: 1920
#im_height: 1080
#
out_width: 640
out_height: 360
